version: "3.9"


services:
  db:
    image: postgres
    container_name: /drgz_backend
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - drgz:/var/lib/postgresql/data


volumes:
  drgz:
